import { ThemeProvider } from '@/lib/providers/theme-provider';
import './globals.css';
import type { Metadata } from 'next';
import { DM_Sans } from 'next/font/google';
import { twMerge } from 'tailwind-merge';
import { SocketProvider } from '@/lib/providers/socket-provider';
import { AppStateProvider } from '@/lib/providers/state-provider';

const inter = DM_Sans({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  //CHALLENGE Files keep reseting when we change between workspaces.
  //CHALLENGE How to cache 
  return (
    <html lang="en">
      <body className={twMerge('bg-background', inter.className)}>
        <ThemeProvider
          attribute="class"
          defaultTheme="dark"
          enableSystem
        >
          <AppStateProvider>
            <SocketProvider>{children}</SocketProvider>
          </AppStateProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
