import { ThemeProvider } from '@/lib/providers/theme-provider';
import './globals.css';
import type { Metadata } from 'next';
import { DM_Sans } from 'next/font/google';
import { twMerge } from 'tailwind-merge';
import { SocketProvider } from '@/lib/providers/socket-provider';
import { AppStateProvider } from '@/lib/providers/state-provider';
import { Toaster } from '@/components/ui/toaster';
import { SubscriptionModalProvider } from '@/lib/providers/subscription-modal-provider';
import { getActiveProductsWithPrices } from '@/lib/supabase/queries';
import { createServerComponentClient } from '@supabase/auth-helpers-nextjs';
import { cookies } from 'next/headers';

const inter = DM_Sans({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
/**
 * CHALLENGES 
  1 Files keep reseting when we change between workspaces.
  2 Real time workspaces
  3 WHEN YOU trash a folder files are also trashed but now when you try to
  4 WHEN SOMEONE IS ADDED AS A WORKSPACE COLLABORATOR THEN you need to create the real time feature.
  5 Include number of collaborators in Plan Usage
 */
  

  return (
    <html lang="en">
      <body className={twMerge('bg-background', inter.className)}>
        <ThemeProvider
          attribute="class"
          defaultTheme="dark"
          enableSystem
        >
          <AppStateProvider>
            <SocketProvider>
              {children}
              <Toaster />
            </SocketProvider>
          </AppStateProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
