import { ThemeProvider } from '@/lib/providers/theme-provider';
import './globals.css';
import type { Metadata } from 'next';
import { DM_Sans } from 'next/font/google';
import { twMerge } from 'tailwind-merge';
import { SocketProvider } from '@/lib/providers/socket-provider';
import { FolderProvider } from '@/lib/providers/file-provider';

const inter = DM_Sans({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={twMerge('bg-background', inter.className)}>
        <ThemeProvider
          attribute="class"
          defaultTheme="dark"
          enableSystem
        >
          <FolderProvider>
            <SocketProvider>{children}</SocketProvider>
          </FolderProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
